// Package evidence owns the evidence binding contract shared by Runtime,
// transition validation, Quality Gates, Controller selection, Manual output,
// and semantic conformance checks.
package evidence

import (
	"fmt"
	"sort"
	"strings"
)

// GeneratorSpec describes evidence generated by the harness rather than
// persisted as a Runtime artifact. Reference is the exact binding accepted by
// transition validation and emitted by Controller/Manual guidance.
type GeneratorSpec struct {
	Name        string
	Reference   string
	Description string
}

// SlotSpec describes one required_evidence slot. AcceptedKinds are the
// persisted Runtime kinds and legacy compatibility aliases that may satisfy
// the slot. A generated slot is satisfied by the metadata in Generator and
// does not need a registered Runtime artifact.
type SlotSpec struct {
	AcceptedKinds []string
	// PreferredKinds are compatible kinds that should win when more than one
	// candidate can satisfy the slot. The order is not significant; callers
	// use membership as a preference signal.
	PreferredKinds []string
	Generator      *GeneratorSpec
}

// Catalog is the immutable evidence compatibility catalog. The catalog keeps
// persisted kinds separate from requirement slots: a *_record value in the
// Loop Definition is a binding slot, not a kind that can necessarily be
// registered with `runtime evidence add`.
type Catalog struct {
	registeredKinds map[string]struct{}
	importableKinds map[string]struct{}
	slots           map[string]SlotSpec
}

func newDefaultCatalog() Catalog {
	registered := make(map[string]struct{}, len(defaultRegisteredKinds))
	for _, kind := range defaultRegisteredKinds {
		registered[kind] = struct{}{}
	}
	importable := make(map[string]struct{}, len(defaultImportableKinds))
	for _, kind := range defaultImportableKinds {
		importable[kind] = struct{}{}
	}
	slots := make(map[string]SlotSpec, len(defaultSlots))
	for slot, spec := range defaultSlots {
		spec.AcceptedKinds = append([]string(nil), spec.AcceptedKinds...)
		spec.PreferredKinds = append([]string(nil), spec.PreferredKinds...)
		if spec.Generator != nil {
			generator := *spec.Generator
			spec.Generator = &generator
		}
		slots[slot] = spec
	}
	return Catalog{registeredKinds: registered, importableKinds: importable, slots: slots}
}

var defaultCatalog = newDefaultCatalog()

// DefaultCatalog returns the repository's single evidence compatibility
// catalog. Returned slices are copied by accessors so consumers cannot mutate
// the shared source of truth.
func DefaultCatalog() Catalog { return defaultCatalog }

// IsRegisteredKind reports whether kind is a legal persisted Runtime evidence
// kind. Requirement slot names are intentionally not accepted here.
func (c Catalog) IsRegisteredKind(kind string) bool {
	_, ok := c.registeredKinds[strings.TrimSpace(kind)]
	return ok
}

// RegisteredKinds returns all legal persisted Runtime evidence kinds in
// deterministic order.
func (c Catalog) RegisteredKinds() []string {
	kinds := make([]string, 0, len(c.registeredKinds))
	for kind := range c.registeredKinds {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)
	return kinds
}

// ImportableKinds returns the evidence kinds allowed by the recovery import
// trust boundary in deterministic order. This allowlist is intentionally
// separate from RegisteredKinds: a persisted kind is not automatically safe
// to trust when imported from an external artifact set.
func (c Catalog) ImportableKinds() []string {
	kinds := make([]string, 0, len(c.importableKinds))
	for kind := range c.importableKinds {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)
	return kinds
}

// IsImportableKind reports whether kind is inside the recovery import trust
// boundary.
func (c Catalog) IsImportableKind(kind string) bool {
	_, ok := c.importableKinds[strings.TrimSpace(kind)]
	return ok
}

// AcceptedKinds returns the kinds accepted for slot. It returns nil for an
// unknown slot and a defensive copy for a known slot.
func (c Catalog) AcceptedKinds(slot string) []string {
	spec, ok := c.slots[strings.TrimSpace(slot)]
	if !ok {
		return nil
	}
	return append([]string(nil), spec.AcceptedKinds...)
}

// PreferredKinds returns the compatible kinds preferred when selecting a
// candidate for slot. It returns nil for an unknown slot and a defensive copy
// for a known slot.
func (c Catalog) PreferredKinds(slot string) []string {
	spec, ok := c.slots[strings.TrimSpace(slot)]
	if !ok {
		return nil
	}
	return append([]string(nil), spec.PreferredKinds...)
}

// IsPreferred reports whether actualKind is a compatible preferred kind for
// slot. Unknown slots and incompatible kinds fail closed.
func (c Catalog) IsPreferred(slot, actualKind string) bool {
	if !c.Accepts(slot, actualKind) {
		return false
	}
	actualKind = strings.TrimSpace(actualKind)
	for _, preferred := range c.PreferredKinds(slot) {
		if preferred == actualKind {
			return true
		}
	}
	return false
}

// RegisteredAcceptedKinds returns only persisted kinds that can be created by
// RecordEvidence for slot. Legacy aliases accepted by in-memory compatibility
// checks are deliberately omitted from operator guidance.
func (c Catalog) RegisteredAcceptedKinds(slot string) []string {
	var kinds []string
	for _, kind := range c.AcceptedKinds(slot) {
		if c.IsRegisteredKind(kind) {
			kinds = append(kinds, kind)
		}
	}
	return kinds
}

// IsGenerated reports whether slot is satisfied by generated evidence rather
// than a registered Runtime artifact.
func (c Catalog) IsGenerated(slot string) bool {
	spec, ok := c.slots[strings.TrimSpace(slot)]
	return ok && spec.Generator != nil
}

// Generator returns the generated-evidence metadata for slot. The returned
// value is copied so callers cannot mutate the immutable catalog.
func (c Catalog) Generator(slot string) (GeneratorSpec, bool) {
	spec, ok := c.slots[strings.TrimSpace(slot)]
	if !ok || spec.Generator == nil {
		return GeneratorSpec{}, false
	}
	return *spec.Generator, true
}

// GeneratorReference returns the canonical generated-evidence binding for
// slot. It returns an empty string when slot is not generated. This accessor
// keeps adapters and other composition-boundary callers on the same catalog
// contract as transition validation.
func (c Catalog) GeneratorReference(slot string) string {
	generator, ok := c.Generator(slot)
	if !ok {
		return ""
	}
	return generator.Reference
}

// HasSlot reports whether slot is declared in the catalog.
func (c Catalog) HasSlot(slot string) bool {
	_, ok := c.slots[strings.TrimSpace(slot)]
	return ok
}

// Accepts reports whether actualKind can satisfy slot. It intentionally
// includes legacy in-memory aliases retained by the compatibility contract;
// only RegisteredKinds may be persisted through runtime evidence add.
func (c Catalog) Accepts(slot, actualKind string) bool {
	actualKind = strings.TrimSpace(actualKind)
	for _, accepted := range c.AcceptedKinds(slot) {
		if accepted == actualKind {
			return true
		}
	}
	return false
}

// ValidateSlots checks that every required evidence slot has a registered
// kind or an explicit generator. It is used by transition and doctor
// conformance so an unexecutable requirement fails closed at load time.
func (c Catalog) ValidateSlots(slots []string) error {
	for _, slot := range slots {
		if !c.HasSlot(slot) {
			return fmt.Errorf("required evidence slot %q is not declared in EvidenceCatalog", slot)
		}
		if generator, generated := c.Generator(slot); generated {
			if strings.TrimSpace(generator.Reference) == "" {
				return fmt.Errorf("required evidence slot %q has an empty generator reference", slot)
			}
			continue
		}
		registered := false
		for _, kind := range c.AcceptedKinds(slot) {
			if c.IsRegisteredKind(kind) {
				registered = true
				break
			}
		}
		if !registered {
			return fmt.Errorf("required evidence slot %q has no registered kind or generator", slot)
		}
	}
	return nil
}

// MissingBindingMessage returns the actionable recovery text shared by the
// transition engine and CLI-facing errors.
func (c Catalog) MissingBindingMessage(transitionID, slot string) string {
	accepted := c.RegisteredAcceptedKinds(slot)
	if generator, generated := c.Generator(slot); generated {
		return fmt.Sprintf("transition %s is missing evidence binding %s; retry with --evidence %s=%s (%s)", transitionID, slot, slot, generator.Reference, generator.Description)
	}
	return fmt.Sprintf("transition %s is missing evidence binding %s; retry with --evidence %s=<reference>; accepted evidence kinds: %s; run `loop-harness explain %s` for current candidates",
		transitionID, slot, slot, formatKinds(accepted), transitionID)
}

func formatKinds(kinds []string) string {
	formatted := make([]string, len(kinds))
	for i, kind := range kinds {
		formatted[i] = "`" + kind + "`"
	}
	return strings.Join(formatted, ", ")
}

var defaultRegisteredKinds = []string{
	"acceptance",
	"agent_activation",
	"agent_completion",
	"agent_readback",
	"bug",
	"builder_report",
	"change_impact",
	"clean_round",
	"completion_report",
	"delivery_review",
	"document_review",
	"e2e_review",
	"human_decision",
	"planning_contract",
	"planning_design",
	"planning_task",
	"qa_review",
	"release_audit",
	"review_result",
	"finding",
	"observation_batch",
	"team_manifest",
	"targeted_reverification",
}

// defaultImportableKinds is an explicit recovery trust boundary. Keep this
// list separate from defaultRegisteredKinds so adding a new persisted kind
// does not silently make untrusted external evidence importable.
var defaultImportableKinds = []string{
	"acceptance",
	"bug",
	"builder_report",
	"change_impact",
	"clean_round",
	"completion_report",
	"delivery_review",
	"document_review",
	"e2e_review",
	"human_decision",
	"planning_contract",
	"planning_design",
	"planning_task",
	"qa_review",
	"release_audit",
	"review_result",
	"finding",
	"observation_batch",
	"targeted_reverification",
}

var defaultSlots = map[string]SlotSpec{
	"req_lock_record": {
		AcceptedKinds: []string{"human_decision"},
	},
	"loop_authorization_record": {
		AcceptedKinds: []string{"human_decision"},
	},
	"human_decision_record": {
		AcceptedKinds: []string{"human_decision"},
	},
	"pause_record": {
		AcceptedKinds: []string{"human_decision", "pause"},
		Generator: &GeneratorSpec{
			Name:        "pause_checkpoint",
			Reference:   "generated:pause_checkpoint",
			Description: "generated pause checkpoint",
		},
	},
	"activation_record": {
		AcceptedKinds: []string{"agent_activation"},
	},
	"builder_report_record": {
		AcceptedKinds: []string{"builder_report", "agent_completion"},
	},
	"team_manifest_record": {
		AcceptedKinds:  []string{"builder_report", "team_manifest", "team_manifest_record"},
		PreferredKinds: []string{"team_manifest", "team_manifest_record"},
	},
	"completion_report": {
		AcceptedKinds: []string{"agent_completion", "completion_report"},
	},
	"document_review_record": {
		AcceptedKinds: []string{"document_review", "document_review_record"},
	},
	"contract_set_record": {
		AcceptedKinds: []string{"document_review", "document_review_record"},
	},
	"task_batch_record": {
		AcceptedKinds: []string{"document_review", "document_review_record"},
	},
	"planning_design_record": {
		AcceptedKinds: []string{"planning_design", "planning_design_record"},
	},
	"planning_contract_record": {
		AcceptedKinds: []string{"planning_contract", "planning_contract_record"},
	},
	"planning_task_record": {
		AcceptedKinds: []string{"planning_task", "planning_task_record"},
	},
	"delivery_review_record": {
		AcceptedKinds: []string{"delivery_review", "delivery_review_record"},
	},
	"qa_review_record": {
		AcceptedKinds: []string{"qa_review", "qa_review_record"},
	},
	"e2e_review_record": {
		AcceptedKinds: []string{"e2e_review", "e2e_review_record"},
	},
	"review_result_record": {
		AcceptedKinds:  []string{"review_result", "delivery_review", "qa_review", "e2e_review", "review_result_record"},
		PreferredKinds: []string{"review_result"},
	},
	"finding_record": {
		AcceptedKinds: []string{"finding", "bug", "finding_record"},
	},
	"observation_batch_record": {
		AcceptedKinds: []string{"observation_batch", "observation_batch_record"},
	},
	"bug_batch_record": {
		AcceptedKinds: []string{"bug", "bug_batch_record"},
	},
	"root_cause_record": {
		AcceptedKinds: []string{"bug", "root_cause_record"},
	},
	"repair_record": {
		AcceptedKinds: []string{"bug", "repair_record"},
	},
	"targeted_reverification_record": {
		AcceptedKinds: []string{"targeted_reverification", "targeted_reverification_record"},
	},
	"clean_round_record": {
		AcceptedKinds: []string{"clean_round", "clean_round_record"},
	},
	"acceptance_record": {
		AcceptedKinds: []string{"acceptance", "acceptance_record"},
	},
	"release_audit_record": {
		AcceptedKinds: []string{"release_audit", "release_audit_record"},
	},
	"change_impact_record": {
		AcceptedKinds: []string{"change_impact"},
	},
}
